export const initialValues = {
  evolutionType: "FRETNET",
  title: "evolution recommadation",
  recommendedBy: " assia ",
  status: " assia ",
  module: "Informatique",
  phase: "PHASE_1",
  application: "GPLOG",
  channelType: "CODIR",
  exploitationType: "INTERNE",
  priority: "1",
  needMeeting: "true",
  planifiedMeetingDate: "23/08/23",
  meetingDate: "23/08/23",
  productionDate: "02/10/23",
  percentage: "10",
  stuationType: "EN_INSTANCE",
  observation: "en cours",
};
